package it.unicam.lcp.ludicolo.actions.moves;

public enum SideEffectType {
    SOURCE_STAGE_INCREASE, SOURCE_STAGE_DECREASE, TARGET_STAGE_INCREASE, TARGET_STAGE_DECREASE, FLINCH, BURN, FREEZE, PARALYSIS, CONFUSION, SLEEP, POISON, BAD_POISON
}
